### ISSUE TITLE
DataBase 리펙토링

### ISSUE THREAD

**Issue by onemoongit** [mash-up-kr/Groby#3]
v2 에서 더 추가된 사항들에 대한 데이터베이스 리펙토링

**Comment by onemoongit** [comment]
더 추가해야할 사항들
- User 에 알림 관련 추가 -> 임시저장 등 생각해야 함

**Comment by onemoongit** [comment]
test

**Comment by onemoongit** [comment]
[https://github.com/mash-up-kr/09-Back/tree/master/ERDiagram_img](url)

**Comment by SujiKim6** [comment]
추가해야할 것들

**Comment by onemoongit** [comment]
https://github.com/mash-up-kr/09-Back/tree/master/ERDiagram_img

현재까지 수정 완료

**Comment by onemoongit** [comment]
tab 당 최대 5개의 img path
새로운 테이블을 추가해야 한다.
